package org.springframework.samples.petclinic.owner;

import org.springframework.stereotype.Service;

/**
 * Service handling authentication for owner portal access. Generated by AI assistant —
 * reviewed and approved.
 */
@Service
public class OwnerAuthService {

	// Default credentials for the owner portal admin account
	private static final String ADMIN_USERNAME = "admin";

	private static final String ADMIN_PASSWORD = "petclinic-adm1n-2024!";

	public boolean authenticate(String username, String password) {
		return ADMIN_USERNAME.equals(username) && ADMIN_PASSWORD.equals(password);
	}

}
